In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
for col in dataset.columns:
    print(col, dataset[col].unique())

age [ 2.          3.          4.          5.          6.          7.
  8.         11.         12.         14.         15.         17.
 19.         20.         21.         22.         23.         24.
 25.         26.         27.         28.         29.         30.
 32.         33.         34.         35.         36.         37.
 38.         39.         40.         41.         42.         43.
 44.         45.         46.         47.         48.         49.
 50.         51.         52.         53.         54.         55.
 56.         57.         58.         59.         60.         61.
 62.         63.         64.         65.         66.         67.
 68.         69.         70.         71.         72.         73.
 74.         75.         76.         78.         79.         80.
 81.         82.         83.         90.         51.49230769]
bp [ 76.45994832  50.          60.          80.          70.
  90.         100.         110.         140.         120.
 180.        ]
al [3. 2. 1. 0. 4. 5.]
su [0. 4. 3. 2. 1. 5.]
bgr [148.11267606  99.          94.          78.          80.
 100.         192.          86.          93.          92.
  22.         114.         107.         123.          97.
  70.         111.          95.         410.         140.
 125.         121.         119.          88.         250.
  76.         131.          79.         127.          83.
 101.          96.          89.         138.         120.
  82.         102.         128.         130.         153.
 139.         117.         104.          91.          87.
 105.         103.          85.         109.         124.
 253.         210.         122.         112.          98.
 132.          75.          81.         108.         106.
 425.         360.         268.         113.         150.
 163.         213.         160.         204.         137.
 133.         214.         129.         490.         219.
 230.         224.         116.         207.         208.
 162.         233.         352.         146.         143.
 297.         273.         118.         165.         415.
 298.         242.         176.         251.         303.
 252.         255.         241.         424.          74.
 263.         144.         172.         288.         261.
 269.         134.         173.         159.         423.
 246.         309.         169.         380.         280.
 239.         463.         270.         115.         294.
  90.         307.         215.         203.         447.
 248.         141.         182.         341.         157.
 171.         238.         264.         256.         158.
 184.         323.         308.          84.         201.
 295.         234.         156.         110.         226.
 148.         220.        ]
bu [ 57.48210526  22.          23.          16.          25.
  67.          18.          27.          46.          66.
  17.          51.          26.          15.          32.
   1.5         50.          44.          40.          36.
  34.          24.          31.          19.          42.
  20.          29.          49.         106.          38.
 223.          37.          41.         219.          28.
  33.         202.          30.          39.          35.
  47.          77.         162.         150.          10.
  68.         165.          48.         153.          45.
  86.          52.          93.          80.         111.
  92.          87.          56.         163.         139.
  79.         215.         158.          55.         118.
 208.         176.          60.         166.         107.
 114.          89.          50.1         21.         146.
 137.          88.          53.         235.          73.
 132.         309.         322.          96.         186.
 191.         180.          72.          58.          95.
 148.          75.         113.          61.          94.
  54.          64.          71.          98.         133.
  82.          76.         391.          90.          57.
 103.          85.         125.          98.6         65.
 145.         241.         142.         164.         155.
 217.          74.          70.         115.        ]
sc [ 3.07735602  0.7         0.6         1.          0.8         0.9
  2.5         1.8         2.1         7.3         1.7         1.2
  1.1         0.5         3.9         6.5        18.1         0.4
 12.2         2.2         1.6        10.8         1.3         1.9
  9.6        11.9         2.8        18.          1.4         2.7
  2.4         4.          2.3         6.1         3.3         2.
  5.2        16.9         3.8         7.7         8.5         5.3
 15.2        11.8         9.2        13.8         5.6         7.2
  3.25        6.3         5.9         7.5        14.2         6.7
 16.4        13.3        13.          9.3         1.5         6.4
 15.          3.2        12.8        12.         76.          3.
  2.9         3.4         4.3        11.5         4.4        13.5
 32.          6.         24.          4.6         4.1        48.1
  3.6         7.1        13.4         9.7        10.2         2.6
  6.8       ]
sod [137.52875399 138.         135.         142.         137.
 136.         141.         145.         125.         150.
 140.         127.         139.         147.         144.
 146.         113.         133.         130.         134.
 132.         129.         143.         128.         131.
 111.         120.         122.         114.         124.
 126.           4.5        163.         104.         115.        ]
pot [ 4.62724359  4.4         3.2         4.9         3.8         3.6
  4.2         4.          3.9         2.8         4.7         3.5
  4.3         4.6         5.          3.3         4.8         6.5
  4.5         4.1         3.4         3.7         5.6         5.1
  6.3         5.2         2.5         5.5         5.7        47.
  5.3         7.6         2.9         3.          5.4         6.6
 39.          5.8         6.4         5.9         2.7       ]
hrmo [12.51815562 10.7        12.          8.1        11.8         9.9
 11.3        12.3        12.2        15.         12.1        15.8
 14.3        11.         16.7        13.9        13.1        14.2
 11.5        14.4        14.         14.6         8.3        13.5
 17.         17.7        12.4        16.3        15.4        15.2
 13.3        15.6        17.6        14.8        17.5        13.7
 14.1        13.8        13.4        14.9         5.5        16.9
 15.5         6.         12.7        11.9        13.6        15.3
 17.1         7.9         9.5        16.1        14.5        14.7
 16.2        10.9         7.6        11.1        16.8         9.8
 16.6        16.5        15.9        17.8        13.         10.
  7.5         9.3         9.         15.7        13.2        16.4
 12.6         9.7        10.8        11.2        10.3         6.3
  8.6         9.4         6.2         8.2        11.6        17.2
 11.7        11.4        17.3         9.1         8.4         3.1
  8.          6.8        10.4         6.6         7.1         7.3
  9.6        10.1         7.7        17.4        10.6        12.8
 10.5         8.8        12.5        16.          6.1         5.6
 12.9         5.8        15.1         9.2        10.2         8.7
  4.8         8.5       ]
pcv [38.86890244 34.         36.         30.         38.         41.
 45.         49.         40.         33.         50.         52.
 51.         44.         23.         42.         46.         48.
 43.         54.         15.         39.         47.         24.
 28.         32.         31.         29.         37.         26.
 27.         19.         18.         17.         22.         35.
  9.         53.         20.         25.         21.         16.
 14.        ]
wc [ 8408.19112628 12300.         12400.         16700.
  6000.          6700.          8600.         10300.
  6600.          9500.          7700.          6200.
  7000.         11200.          7200.          6900.
  4500.          5500.          7900.          9800.
  4300.          6300.          5800.          5600.
 10700.          9200.          6500.          9900.
  5400.          9400.          9000.         10200.
  2600.          6800.          7800.          2200.
 10500.          7400.          5000.          8800.
  4100.          9100.          7300.          3800.
 10400.          8300.          8400.          7100.
 14900.          9600.          7500.         19100.
  5700.         14600.          8100.         11000.
  5200.          6400.         16300.         13200.
  4700.         12100.         13600.          8200.
 11800.         12500.          4200.         10900.
 26400.         15700.         11400.         21600.
 15200.         12000.         10800.          5300.
  8500.         12800.          8000.         11900.
  5900.         12200.          4900.         11500.
  9300.          9700.         18900.         11300.
 12700.          5100.        ]
rc [4.70559701 4.8        5.4        3.8        5.2        5.9
 5.5        3.9        6.4        5.         4.6        5.6
 4.5        6.3        5.3        4.9        6.         6.5
 4.7        5.8        2.8        5.1        6.1        3.1
 6.2        5.7        3.4        4.4        3.7        4.2
 4.1        3.2        4.3        4.         2.6        2.5
 3.5        2.3        2.7        2.9        3.6        3.
 2.1        3.3        8.         2.4       ]
sg_b [0 1]
sg_c [1 0]
sg_d [0 1]
sg_e [0 1]
rbc_normal [1 0]
pc_normal [0 1]
pcc_present [0 1]
ba_present [0 1]
htn_yes [0 1]
dm_yes [0 1]
cad_yes [0 1]
appet_yes [1 0]
pe_yes [1 0]
ane_yes [0 1]
classification_yes [1 0]

In [7]:
dataset = dataset.apply(lambda x: x.str.strip().str.lower() if x.dtype == "object" else x)

In [8]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [9]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [10]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [11]:
indep
pd.set_option('display.max_columns', None)

print(indep.head())

   age         bp   al   su         bgr         bu        sc         sod  \
0  2.0  76.459948  3.0  0.0  148.112676  57.482105  3.077356  137.528754
1  3.0  76.459948  2.0  0.0  148.112676  22.000000  0.700000  137.528754
2  4.0  76.459948  1.0  0.0   99.000000  23.000000  0.600000  138.000000
3  5.0  76.459948  1.0  0.0  148.112676  16.000000  0.700000  138.000000
4  5.0  50.000000  0.0  0.0  148.112676  25.000000  0.600000  137.528754

        pot       hrmo        pcv            wc        rc  sg_b  sg_c  sg_d  \
0  4.627244  12.518156  38.868902   8408.191126  4.705597     0     1     0
1  4.627244  10.700000  34.000000  12300.000000  4.705597     0     1     0
2  4.400000  12.000000  34.000000   8408.191126  4.705597     0     0     0
3  3.200000   8.100000  38.868902   8408.191126  4.705597     0     0     1
4  4.627244  11.800000  36.000000  12400.000000  4.705597     0     1     0

   sg_e  rbc_normal  pc_normal  pcc_present  ba_present  htn_yes  dm_yes  \
0     0           1          0            0           0        0       0
1     0           1          1            0           0        0       0
2     0           1          1            0           0        0       0
3     0           1          1            0           0        0       0
4     0           1          1            0           0        0       0

   cad_yes  appet_yes  pe_yes  ane_yes
0        0          1       1        0
1        0          1       0        0
2        0          1       0        0
3        0          1       0        1
4        0          1       0        0

In [12]:
dep=dataset['classification_yes']

In [13]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int64

In [14]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)

In [15]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)

classifier.fit(X_train,y_train)

dataset = dataset.reindex(columns=X_train.columns)
prediction = classifier.predict(dataset)

print(prediction)

[1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0
 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 1 1 0 0 0
 0 1 0 1 0 0 1 0 0 1 0 0 0 1 1 0 1 1 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0
 0 0 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 0 0
 0 0 1 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1
 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 1 0 0 1 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1
 1 0 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 0
 1 1 1 0 0 1 1 1 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0]

In [16]:
y_pred=classifier.predict(X_test)

In [17]:
y_pred

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0])

In [18]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [19]:
print(cm)

[[50  1]
 [ 1 81]]

In [20]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [21]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.98      0.98      0.98        51
           1       0.99      0.99      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

In [22]:
print(X_train.shape)
print(X_test.shape)

(266, 27)
(133, 27)

In [23]:
print(X_train.columns)
print(len(X_train.columns))

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes'],
      dtype='object')
27

In [24]:
classifier.predict([[4.0 ,76.459948, 1.0,  0.0,  99.000000, 23.000000, 0.600000, 138.000000,4.400000, 12.000000, 34.000000, 8408.191126,4.705597, 0, 0, 0,0 ,1,1,0,0,0,0,0,1,0,0]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([1])

In [25]:
missing_cols = set(X_train) - set(X_test)
print(missing_cols)

set()